spring:
  profiles:
    active: docker
  resources:
    chain:
      cache: false
fido2:
  rp:
    id: localhost
    origin: localhost
    port: 8080
    ssl:
      key-store: classpath:keystore/fido_cert.p12
      key-store-type: PKCS12
      key-alias: fido
      key-store-password: fido@123
conformance:
  url: https://localhost:8080
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.linecorp.line: DEBUG
fido2-server:
  host: fido2

